### ISSUE TITLE
refactor: revert assignment of oldmarr widget mapping

### ISSUE THREAD

**Issue by Meierschlumpf** [homarr-labs/homarr#1079]
See comment in old-import/src/widgets/definitions/index.ts

> revert assignment so that only old widgets are needed in the object,
> this can be done ones all widgets are implemented

Created because of #1019

**Comment by SeDemal** [comment]
https://github.com/homarr-labs/homarr/pull/844/commits/ab94cdc0d4045c21e86d47de87535aecca014686#diff-e4e0568b34d327d40cdc4761d37aa3dc6c7b2675ba4315df004beed2f55cae8c

Same here
