### ISSUE TITLE
System Health Monitoring

### ISSUE THREAD

**Issue by hillaliy** [homarr-labs/homarr#1093]

**Comment by hillaliy** [comment]
https://github.com/homarr-labs/homarr/issues/655

**Comment by SeDemal** [comment]
Hold up, sorry I only saw this now, this widget might be part of https://github.com/homarr-labs/homarr/pull/848
@homarr-labs/maintainers What do you think?

**Comment by hillaliy** [comment]
OMV integration is ready.
@homarr-labs/maintainers What do you think?

**Comment by hillaliy** [comment]
feat: Health monitoring widget #1144
