### ISSUE TITLE
bug: tiles order not respected on firefox

### ISSUE THREAD

**Issue by SeDemal** [homarr-labs/homarr#1102]
### Provide environment information

Development Environment
Firefox

### Describe the bug

Upon entering a board right after starting `pnpm dev`, the items won't be in the right place.
Editing the board in this state will result in all kinds of weird placement issues.

Actually self corrects directly after refreshing the page it seems.
Don't know if there's another way to get to that state that may cause problem to the standard user.

### To reproduce

pnpm dev and reload the board page while it's starting up.

### Additional information

![image](https://github.com/user-attachments/assets/54828ede-95de-49f7-9f62-39907728bc05)

**Comment by Meierschlumpf** [comment]
Tried something else than dynamic, but it seems not to be the reason why it's not working. After changing the dynamic thing to `useSuspenseQuery` I got the same result

**Comment by Meierschlumpf** [comment]
It has to be related to a combination between suspense and gridstack. They don't seem to like each other... Even when I put the `item.kind` into a suspense placed into a gridstack-item it has the wrong positions...

**Comment by simono41** [comment]
> Tried to fix it with react portals. It did not work at all

Could it also be that the import of the dashboard from the old Homarr version did not work? I will create an issue separately with the exact error message.

**Comment by Mx772** [comment]
> > Tried to fix it with react portals. It did not work at all
> 
> Could it also be that the import of the dashboard from the old Homarr version did not work? I will create an issue separately with the exact error message.

For what it's worth, I had a clean (no import) and have this issue.

**Comment by Meierschlumpf** [comment]
I found the issue and **OMG IS THIS BUG STUPID!**

**Comment by Mx772** [comment]
> I found the issue and **OMG IS THIS BUG STUPID!**

Oh that's a funny one. 

Also it's Christmas Eve, you got better things to do! Lol
