### ISSUE TITLE
bug: Not working on ARM64

### ISSUE THREAD

**Issue by MaienM** [homarr-labs/homarr#1125]
### Provide environment information

I'm trying to use the docker image, but it's failing so early in the process that I cannot open a shell in this and run the requested command inside the container. I did run it on the machine that I'm attempting to run the container on, but keep in mind that a lot of this information is useless/misleading; the listed binaries are obviously not actually the ones that will be used in the container. 

```
  System:
    OS: Linux 6.1 NixOS 24.11 (Vicuna) 24.11 (Vicuna)
    CPU: (4) arm64 Cortex-A76
    Memory: 4.73 GB / 7.84 GB
    Container: Yes
    Shell: 5.2.26 - /nix/store/w7fy8y8a296hi61nibl62xgnfwd2nfw5-bash-interactive-5.2p26/bin/bash
  Binaries:
    Node: 22.4.1 - /nix/store/2c0qimdjslxal42s4m10zj95f9r11l4l-nodejs-22.4.1/bin/node
    npm: 10.8.1 - /nix/store/2c0qimdjslxal42s4m10zj95f9r11l4l-nodejs-22.4.1/bin/npm
```

### Describe the bug

The `arm64` image doesn't actually appear to be valid `arm64`, and running it on a machine with that architecture results in `exec /usr/local/bin/docker-entrypoint.sh: exec format error`.

### Link to reproduction

N/A

### To reproduce

Attempt to start the image on a machine with an `arm64` architecture.

### Additional information

I suspect that this is due to the dockerfile specifically using an `amd64` image regardless of what platform it's being built for:

https://github.com/homarr-labs/homarr/blob/7059a3d88f73ddceb70d037bb0f362fe50bda225/Dockerfile#L1

This is probably fine for the first two steps (`builder` and `installer`), but this same image is also used for the `runner` part which I think results in the final image being based on an `amd64` image even for the `arm64` image:

https://github.com/homarr-labs/homarr/blob/7059a3d88f73ddceb70d037bb0f362fe50bda225/Dockerfile#L61

**Comment by ajnart** [comment]
Hi @MaienM as far as I've heard from the rest of the team, arm64 is not currently 100% supported/tested. If you'd like to, you could fork the repository and commit the changes you're suggesting so that it runs the CI and creates a docker image that you can test for yourself. Then you can tell us / open a PR with exactly the right changes needed to fix this issue. It would be a big help if you could manage to make it work.
