### ISSUE TITLE
feat: Current state of this project?

### ISSUE THREAD

**Issue by CrazyWolf13** [homarr-labs/homarr#1127]
### Describe the feature you'd like to request

Hi

I'm asking what the current state of this project (v1.0) is, are we talking about weeks till ETA or are we talking about months/years till completion?
I'm known of the other repo by ajnart of the 0.X homarr.

Sorry to ask like this here, and hope it does not sound rude, but I'm currently in a near complete rebuild of my homelab and have used dashy (~~am~~ was a core contributor of it) as dashy has had a hard time keeping up, and the owner barely fixing critical bugs, the project has slowly become obsolete and broken, so I'm considering a full switch to homarr, however if homarr 1.0 will release in an appropriate time, I won't bother to first configure for v0.X and then for v1.x again, as I guess there will be breaking changes.

Thanks for a little update :)
Greetings from Switzerland 🇨🇭

### Describe the solution you'd like to see

-

**Comment by SeDemal** [comment]
https://github.com/homarr-labs/homarr/issues/655
That's about how far we are in terms of widgets. there's always bits and bobs here and there.
Contribution on v0.15 are not wasted as they are ultimately ported to v1, but they need to be manually ported.
You are welcome to try and contribute to V1 directly, but I'm not sure the permissions allow for that.

**Comment by CrazyWolf13** [comment]
Oh I see, thanks!

Yeahs seems quite a lot has already been done :)

I'd love to contribute, but currently know too less to be helpful here :/.

I was just trying to evaluate if there is any reasonable sense on switching to homarr now or better waiting for v1.

Haha everyone from switzerland here 😅

**Comment by SeDemal** [comment]
Oh you can without a doubt change to homarr now, We have an importation system from the old version to make the transition as painless as possible.

Most of what we do is porting old functions into a proper structure and properly rewriting it. No pressure to contribute, be free to just enjoy too.

Swiss are everywhere

**Comment by CrazyWolf13** [comment]
Ohhh that's awesome!

Thanks!!
