### ISSUE TITLE
feat: remove url variables

### ISSUE THREAD

**Issue by manuel-rw** [homarr-labs/homarr#1436]
In https://github.com/ajnart/homarr/issues/2189 we voted against the variables.
Therefore, we should remove them in 1.0.

**Comment by j3lte** [comment]
I wasn't aware of the [vote](https://github.com/ajnart/homarr/issues/2189#issuecomment-2457753537), I was the one building the feature for variables. As I've read the comments about 'just duplicate the boards' (which is what I did in the first place and why I built the variables), it seems I have wasted time building it in the first place...

**Comment by manuel-rw** [comment]
Hi, sorry that eventually we decided against it. Homarr will always be open source, so feel free to fork if you want this feature regardless. Thank you for your understanding
