### ISSUE TITLE
bug: media request search engine (eg. jellyseerr) do not accept spaces

### ISSUE THREAD

**Issue by manuel-rw** [homarr-labs/homarr#1675]
### Provide environment information

  System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 5.55 GB / 31.91 GB
  Binaries:
    Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.14.4 - ~\AppData\Local\pnpm\pnpm.CMD

### Describe the bug

The search engine does not accept search terms that contain spaces.

### Link to reproduction

N/A

### To reproduce

N/A

**Comment by Meierschlumpf** [comment]
Closed in #1637
