### ISSUE TITLE
bug: startup fails with permission denied

### ISSUE THREAD

**Issue by Meierschlumpf** [homarr-labs/homarr#1699]
### Provide environment information

-

### Describe the bug

For certain users the shell startup script fails with permission denied to create the directories db and redis in `/appdata`. We suspect it to be a problem with docker permissions as we use user `1001:1001` internally

### Link to reproduction

-

### To reproduce

Use ubuntu machine and run the image locally.

**Comment by siedenburg2** [comment]
Got the same problem, my appdata folder got permissions for "nobody", changed that and now the site itself works
