### ISSUE TITLE
bug: Cannot create tables using mysql2 syntax

### ISSUE THREAD

**Issue by simono41** [homarr-labs/homarr#1701]
### Provide environment information

Docker arm64 on this Host:

  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (18) arm64 Neoverse-N1
    Memory: 26.76 GB / 62.68 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm

### Describe the bug

The Docker image can establish a connection to MariaDB Server version 11, but unfortunately there are some errors in the SQL syntax

### Link to reproduction

-

### To reproduce

Launched the Docker image via Docker Compose.

### Additional information

![grafik](https://github.com/user-attachments/assets/ca9956b7-6a16-4b86-8260-67ff56f0882e)

![grafik](https://github.com/user-attachments/assets/3b116544-1f50-4a67-9391-1eb925e4e22c)

**Comment by Meierschlumpf** [comment]
We don't support maria-db
