### ISSUE TITLE
bug: DB_URL not parsed correctly

### ISSUE THREAD

**Issue by simono41** [homarr-labs/homarr#1702]
### Provide environment information

Docker arm64 on this Host:

System:
OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
CPU: (18) arm64 Neoverse-N1
Memory: 26.76 GB / 62.68 GB
Container: Yes
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.19.0 - /usr/bin/node
npm: 9.2.0 - /usr/bin/npm

### Describe the bug

Apparently the DB_URL cannot be parsed properly.

### Link to reproduction

-

### To reproduce

Launched the Docker image via Docker Compose.

### Additional information

![grafik](https://github.com/user-attachments/assets/638a4f93-84f4-4e69-b237-1636519329e8)

**Comment by Meierschlumpf** [comment]
Remove the `'` quotion marks on both sides

**Comment by simono41** [comment]
> Remove the `'` quotion marks on both sides

Unfortunately that didn't work - the quota marks are present according to the documentation.

![grafik](https://github.com/user-attachments/assets/a8c1bf33-c40d-4e3e-8b60-8f87a2053308)

**Comment by Meierschlumpf** [comment]
Okay the second one is another problem. This problem is actually something we need to fix
