### ISSUE TITLE
bug: Boards require reimporting after every docker update on beta branch

### ISSUE THREAD

**Issue by darkcloud784** [homarr-labs/homarr#1793]
### Describe the bug

Every docker container update, it requires re-importing or starting from scratch.

### Steps to reproduce

Export boards
update container to current beta branch release
import your boards.
next update, watch as you have to re-import them again.

### Impact

Crazy inefficient, and also requires saving your export token which is a security issue.

### Version

1.0.0-beta

### Installation method

Docker Compose

### Browser

Edge (Chromium)

**Comment by Meierschlumpf** [comment]
@darkcloud784 can you share your `docker-compose.yml` file with any eventual secrets redacted?

**Comment by darkcloud784** [comment]
> @darkcloud784 can you share your `docker-compose.yml` file with any eventual secrets redacted?
I'm using portainer, this is the service in the stack for homarr.

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:beta
    #image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /mnt/Media/containers/homarr/configs:/app/data/configs
      - /mnt/Media/containers/homarr/icons:/app/public/icons
      - /mnt/Media/containers/homarr:/data
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.homarr.entrypoints=websecure"
    - "traefik.http.routers.homarr.rule=Host(`my.domain.com`)"
    - "traefik.docker.network=traefik_default"
    - "traefik.http.services.homarr.loadbalancer.server.port=7575"
    networks:
      - traefik_default
##

**Comment by Meierschlumpf** [comment]
Okay yes your using the wrong volumnes. Instead you would need to use the `/appdata` volume:

Like described in the official 1.0 beta blog post and all other compose files from the new documentation:

See https://deploy-preview-113--homarr-docs.netlify.app/blog/2024/12/17/open-beta-1.0#how-to-use-the-beta-with-docker

**Comment by darkcloud784** [comment]
> Okay yes you're using the wrong volumes. Instead you would need to use the `/appdata` volume:
> 
> Like described in the official 1.0 beta blog post and all other compose files from the new documentation:
> 
> See https://deploy-preview-113--homarr-docs.netlify.app/blog/2024/12/17/open-beta-1.0#how-to-use-the-beta-with-docker

Thanks, I guess I missed that part.
