### ISSUE TITLE
bug: TRPCClientError: error:1C800064:Provider routines::bad decrypt

### ISSUE THREAD

**Issue by darkcloud784** [homarr-labs/homarr#1808]
### Describe the bug

After updating to beta 9, homarr seems to not be able to display any of my integrations and provides the following in the widget.
 
![image](https://github.com/user-attachments/assets/5c79a9cc-e8c5-4667-97a3-8a7ad52cc697)

Likewise in the docker logs it shows the following.

`}
2024-12-29T19:59:00.820Z error Failed to run integration job integration=fy4sobay4gg6fo6ip8oujm29 inputHash='W3t9XQ==' error=Error: error:1C800064:Provider routines::bad decrypt
  at decryptSecretWithKey (/app/apps/tasks/tasks.cjs:434631:50)
  at decryptSecret (/app/apps/tasks/tasks.cjs:434623:10)
  at /app/apps/tasks/tasks.cjs:436212:18
  at Array.map (<anonymous>)
  at /app/apps/tasks/tasks.cjs:436210:54
  at async catchingCallbackAsync (/app/apps/tasks/tasks.cjs:422922:9)
The above error also had these properties on it:
{
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}`

Also want to mention that all my integrations had 2 of each listed even though I only have 1 deployed. Both go to the same URL. I removed one of them thinking it was the issue, but no bueano

### Steps to reproduce

Deploy homarr via portainer stack using beta 8
import old homarr boards
Update to beta 9
after docker container pull it errors.

### Impact

Makes all integrations nonfunctional.

### Version

1.0.0-beta

### Installation method

Portainer

### Browser

Edge (Chromium)

**Comment by Meierschlumpf** [comment]
fuck, okay then the unmounted volume is not persisted over updated. So I'll have to do something about this... Let me think

**Comment by darkcloud784** [comment]
> fuck, okay then the anonymous volume is not persisted over updates. (at least for portainer) So I'll have to do something about this... Let me think

This is my portainer config if it helps:

`  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:beta
    #image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
#      - /mnt/Media/containers/homarr/configs:/appdata/configs
#      - /mnt/Media/containers/homarr/icons:/appdata/public/icons
      - /mnt/Media/containers/homarr:/appdata
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.homarr.entrypoints=websecure"
    - "traefik.http.routers.homarr.rule=Host(`nautiluslab.host`)"
    - "traefik.docker.network=traefik_default"
    - "traefik.http.services.homarr.loadbalancer.server.port=7575"`

**Comment by Meierschlumpf** [comment]
Okay, we'll add a new env variable for decrypting the integration secrets. This will be a breaking change that will break the secrets except somebody copies the previous secret over

**Comment by darkcloud784** [comment]
> Okay, we'll add a new env variable for decrypting the integration secrets. This will be a breaking change that will break the secrets except somebody copies the previous secret over

Is this the token that it creates when exporting?

**Comment by Meierschlumpf** [comment]
No its a token that was created and saved to a file when starting the container the first time. I'll provide a command to extract it in the release notes, so you'll be able to use the previous one (at least when the anonymous volume was not deleted yet...)

**Comment by IIIdefconIII** [comment]
Im having the same error, did you ever got thi solved?
