### ISSUE TITLE
feat: ldap / oidc groups

### ISSUE THREAD

**Issue by Meierschlumpf** [homarr-labs/homarr#708]
### Describe the feature you'd like to request

Link groups of homarr with ldap / oidc by the same name. Additionally also add a create option wherever a group can be selected for admins so they don't need to go to the groups page and add it here.

### Describe the solution you'd like to see

See above

**Comment by MaienM** [comment]
For OIDC please make the claim (field in the token) that is looked at for the list of groups configurable. I see some projects hardcode this to `groups` and while that might be a common name for it this is not universal, it can really be any arbitrary name.

**Comment by Meierschlumpf** [comment]
Hey @MaienM,
Thanks for the comment. In the authentication library we are using are two functions. One of them allows us to have access to the tokens (So for example the id_token and such. The other one to the profile (which for example with AzureAd includes groups and roles for me). Is your intend to read it from the id_token? If so I don't think this is a good way as decoding the content of the token is a bit hacky. What we could do is to add a env variable that allows to for example change it from groups (uuids) to roles (actually understandable names). What is your opinion on this?
